In [1]:
# pip install numpy
import numpy as np

In [2]:
print(type([1,2,3])) # lista
print(type((1,2,3))) # tupla
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [50]:
np.zeros([6,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((1))

array([0.])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.arange(0,100,5) # [0,100[

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [20]:
np.arange(-4, 1)

array([-4, -3, -2, -1,  0])

In [26]:
arreglo = np.arange(0, 10, 0.5)
print(arreglo)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [28]:
print(len(arreglo))
print(arreglo.size)


20
20


In [30]:
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

(2, 3, 4)


In [33]:
arreglo_pares = np.arange(0,20,2)
print(arreglo_pares)

[ 0  2  4  6  8 10 12 14 16 18]


In [34]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [35]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [37]:
arreglo_de_24 = np.arange(24)
print(arreglo_de_24)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [38]:
arreglo_de_24.reshape(12,2)
arreglo_de_24.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [39]:
arreglo_de_24.reshape(6,4)
arreglo_de_24.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
arreglo_de_24.reshape(24,1)
arreglo_de_24.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [41]:
arreglo_de_24.reshape(3,8)
arreglo_de_24.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [51]:
arreglo_de_24.reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [52]:
arreglo_de_24.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [53]:
arreglo_de_24.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [56]:
arreglo_de_24.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [57]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [61]:
a / b

array([2., 2., 2.])

In [65]:
arreglo_tres_dimensiones = np.arange(24).reshape(3,2,4)

In [66]:
arreglo_tres_dimensiones

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [68]:
arreglo_dos_de_tres_dimensiones = np.arange(-24,0,1).reshape(3,2,4)

In [69]:
arreglo_dos_de_tres_dimensiones

array([[[-24, -23, -22, -21],
        [-20, -19, -18, -17]],

       [[-16, -15, -14, -13],
        [-12, -11, -10,  -9]],

       [[ -8,  -7,  -6,  -5],
        [ -4,  -3,  -2,  -1]]])

In [77]:
arreglo_tres_dimensiones+arreglo_dos_de_tres_dimensiones

array([[[-24, -22, -20, -18],
        [-16, -14, -12, -10]],

       [[ -8,  -6,  -4,  -2],
        [  0,   2,   4,   6]],

       [[  8,  10,  12,  14],
        [ 16,  18,  20,  22]]])

In [79]:
# mod
a % b

array([0, 0, 0], dtype=int32)

In [83]:
# mult
print(a*10)
# suma
print(a +7)
# resta
print(a-2)
#

[100 100 100]
[17 17 17]
[8 8 8]


In [84]:
arreglo_muestra = np.arange(20).reshape(5,2,2)
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [148]:
respuesta = (arreglo_muestra >5) &(arreglo_muestra < 12)
respuesta

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [149]:
arreglo_muestra[respuesta]

array([ 6,  7,  8,  9, 10, 11])

In [145]:
respuesta = (arreglo_muestra >5) *(arreglo_muestra < 12) *(arreglo_muestra%2==0)

In [146]:
arreglo_muestra[respuesta]

array([ 6,  8, 10])

In [151]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [152]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [154]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [155]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [156]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [159]:
print(arreglo_doce.sum())
print(arreglo_doce.min())
print(arreglo_doce.max())

66
0
11


In [160]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [161]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [162]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [163]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [178]:
arreglo_doce.reshape(3,2,2)[0,0,0]

1