In [2]:
import numpy as np

In [3]:
arreglo_0_90_grados = np.array([0,30,45,90])

In [5]:
radianes = arreglo_0_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.57079633])

In [6]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 1.        ])

In [7]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 6.12323400e-17])

In [10]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.63312394e+16])

In [12]:
arreglo_random = np.random.randint(11) # [0,11[
arreglo_random

10

In [13]:
arreglo_random = np.random.randint(0,11,4) # [0 minimo , 11 maximo excluido, 4 tamaño
arreglo_random

array([1, 4, 4, 8])

In [14]:
arreglo_random.mean()

4.25

In [15]:
np.median(arreglo_random)

4.0

In [16]:
np.std(arreglo_random)

2.48746859276655

In [17]:
np.var(arreglo_random)

6.1875

In [18]:
np.mean(arreglo_random)

4.25